# Generated by Django 5.0.6 on 2024-06-27 17:18

from django.db import migrations

GROUP_NAME = "Nonlinear Users"


def forward(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    nonlinear_group, _ = Group.objects.get_or_create(name=GROUP_NAME)

    nonlinear_config = apps.get_app_config("nonlinear")
    content_types = ContentType.objects.filter(
        app_label__in=[
            nonlinear_config.label,
        ]
    )
    all_permissions = Permission.objects.filter(content_type__in=content_types)
    nonlinear_config = nonlinear_group.permissions.add(*all_permissions)


def reverse(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nonlinear", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
